//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &'static str {
        "bdk_tx"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq)]
pub struct Model {
    pub idx: i32,
    pub txid: String,
    pub raw_tx: Option<Vec<u8>>,
    pub first_seen: Option<String>,
    pub last_seen: Option<String>,
    pub last_evicted: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Idx,
    Txid,
    RawTx,
    FirstSeen,
    LastSeen,
    LastEvicted,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Idx,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = i32;
    fn auto_increment() -> bool {
        true
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    BdkAnchor,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Idx => ColumnType::Integer.def(),
            Self::Txid => ColumnType::String(StringLen::None).def().unique(),
            Self::RawTx => ColumnType::VarBinary(StringLen::None).def().null(),
            Self::FirstSeen => ColumnType::String(StringLen::None).def().null(),
            Self::LastSeen => ColumnType::String(StringLen::None).def().null(),
            Self::LastEvicted => ColumnType::String(StringLen::None).def().null(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::BdkAnchor => Entity::has_many(super::bdk_anchor::Entity).into(),
        }
    }
}

impl Related<super::bdk_anchor::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BdkAnchor.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
