//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &'static str {
        "bdk_anchor"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq)]
pub struct Model {
    pub idx: i32,
    pub txid: String,
    pub block_height: u32,
    pub block_hash: String,
    pub confirmation_time: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Idx,
    Txid,
    BlockHeight,
    BlockHash,
    ConfirmationTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Idx,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = i32;
    fn auto_increment() -> bool {
        true
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    BdkTx,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Idx => ColumnType::Integer.def(),
            Self::Txid => ColumnType::String(StringLen::None).def(),
            Self::BlockHeight => ColumnType::BigInteger.def(),
            Self::BlockHash => ColumnType::String(StringLen::None).def(),
            Self::ConfirmationTime => ColumnType::String(StringLen::None).def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::BdkTx => Entity::belongs_to(super::bdk_tx::Entity)
                .from(Column::Txid)
                .to(super::bdk_tx::Column::Txid)
                .into(),
        }
    }
}

impl Related<super::bdk_tx::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BdkTx.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
