name: Run tests

on:
  push:
    branches: [ "utexo-master", "dev", "stage", "master", "ks/dev" ]
  pull_request:
    branches: [ "utexo-master", "dev", "stage", "master", "ks/dev" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test_and_coverage:
    timeout-minutes: 120
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Setup rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
      - name: Test with all features
        run: cargo test --all-features

  test_features:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          rustflags: ""
      - name: Test with electrum feature
        run: |
          cargo test --profile reldebug --no-default-features --features electrum get_fee_estimation::success_electrum -- --ignored
          SKIP_INIT=1 cargo test --profile reldebug --no-default-features --features electrum go_online::fail
          SKIP_INIT=1 cargo test --profile reldebug --no-default-features --features electrum send::min_confirmations_electrum
          SKIP_INIT=1 cargo test --profile reldebug --no-default-features --features electrum send::min_relay_fee_electrum
      - name: Test with esplora feature
        run: |
          cargo test --profile reldebug --no-default-features --features esplora get_fee_estimation::success_esplora -- --ignored
          SKIP_INIT=1 cargo test --profile reldebug --no-default-features --features esplora go_online::fail
          SKIP_INIT=1 cargo test --profile reldebug --no-default-features --features esplora send::min_confirmations_esplora
          SKIP_INIT=1 cargo test --profile reldebug --no-default-features --features esplora send::min_relay_fee_esplora
      - name: Test with no default features
        run: cargo test --profile reldebug --no-default-features

  test_doc:
    timeout-minutes: 30
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          rustflags: ""
      - name: Test documentation
        run: |
          cargo test --doc
